tftpAddress:
  ipv4:
    amd64: tftp://192.168.0.1/x86_64/amd64.efi
    arm64: tftp://192.168.0.1/aarch64/arm64.efi
  ipv6:
    amd64: tftp://[2001:db8::1]/x86_64/amd64.efi
    arm64: tftp://[2001:db8::1]/aarch64/arm64.efi
ipxeAddress:
  ipv4:
    amd64: http://192.168.0.2/ipxe/boot4.pxe
    arm64: http://192.168.0.2/ipxe/boot4.pxe
  ipv6:
    amd64: http://[2001:db8::2]/ipxe/boot6.pxe
    arm64: http://[2001:db8::2]/ipxe/boot6.pxe
